# Generated by Django 3.1.6 on 2021-03-10 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customergroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customerpermission',
            name='name',
        ),
        migrations.AddField(
            model_name='customergroup',
            name='description_DE',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='description_EN',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='discipline_DE',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='discipline_EN',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='name_DE',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='name_EN',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='network_manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerpermission',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.customergroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpermission',
            name='model_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpermission',
            name='rights',
            field=models.CharField(choices=[('all', 'View all content'), ('admin', 'Create/edit/delete all content'), ('creator', 'Create/edit/delete owned content'), ('none', 'None')], default='', max_length=24),
            preserve_default=False,
        ),
    ]
