# Generated by Django 3.1.6 on 2021-02-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='roles',
            field=models.CharField(default='', max_length=48),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
    ]
