# Generated by Django 3.1.6 on 2021-03-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210310_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpermission',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='account.customergroup'),
        ),
    ]
