# Generated by Django 3.1.6 on 2021-02-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210220_1024'),
        ('orders', '0006_auto_20210220_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
