# Generated by Django 3.1.6 on 2021-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='bank',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='bic',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='ceo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='court',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='iban',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='owner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='slogan',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='street',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='tax',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='vat',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='zip',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='elements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='is_sticky',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='layout',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='type',
            field=models.CharField(blank=True, default='headerSettings', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='salesordersettings',
            name='collections',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesordersettings',
            name='header',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='salesordersettings',
            name='header_bottom',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='salesordersettings',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesordersettings',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesordersettings',
            name='template_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='salesordersettings',
            name='template_signature',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='salesordersettings',
            name='template_suffix',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='salesordersettings',
            name='template_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesordersettings',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='shopnewsletter',
            name='button_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='shopnewsletter',
            name='popup_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop'),
        ),
        migrations.AlterField(
            model_name='shopnewsletter',
            name='popup_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='shopnewsletter',
            name='target_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shopnewsletter',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='locale',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='shop_hotline',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='shop_tagline',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='shop_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='shop_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shopstyling',
            name='color1',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='shopstyling',
            name='color2',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='shopstyling',
            name='color3',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='shopstyling',
            name='custom_css',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='shopstyling',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='shop'),
        ),
        migrations.AlterField(
            model_name='shopstyling',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop'),
        ),
        migrations.AlterField(
            model_name='shopstyling',
            name='skin_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='shopstyling',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='host',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='port',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='sender_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='user',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='uid',
            name='expenses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uid',
            name='help_desk_tickets',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uid',
            name='inventory',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uid',
            name='payments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uid',
            name='purchase_order',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uid',
            name='sales_order',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uid',
            name='type',
            field=models.CharField(blank=True, default='uidSettings', max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='DeliverySettings',
        ),
    ]
