# Generated by Django 3.1.6 on 2021-03-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('locale', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_title', models.CharField(max_length=128)),
                ('tax_description', models.TextField(null=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=12)),
                ('template', models.CharField(max_length=64)),
                ('html', models.TextField()),
            ],
            options={
                'unique_together': {('lang', 'template')},
            },
        ),
        migrations.CreateModel(
            name='CustomPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=12)),
                ('page_category', models.CharField(max_length=128, null=True)),
                ('page_inner', models.TextField(null=True)),
                ('page_name', models.CharField(max_length=64)),
                ('page_title', models.CharField(max_length=254, null=True)),
            ],
            options={
                'unique_together': {('lang', 'page_name')},
            },
        ),
        migrations.CreateModel(
            name='CustomElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=12)),
                ('element_content', models.TextField(null=True)),
                ('element_location', models.CharField(max_length=128)),
                ('element_title', models.CharField(max_length=128, null=True)),
            ],
            options={
                'unique_together': {('lang', 'element_location')},
            },
        ),
    ]
