# Generated by Django 3.1.6 on 2021-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('signature', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(max_length=24, unique=True)),
                ('acc_number', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.CharField(blank=True, max_length=64, null=True)),
                ('user_password', models.CharField(blank=True, max_length=64, null=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
