# Generated by Django 3.1.6 on 2021-03-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_settings', '0002_deliverysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='locale',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
