# Generated by Django 3.1.5 on 2021-02-07 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '__first__'),
        ('account', '0001_initial'),
        ('product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=256)),
                ('date', models.DateField(auto_now=True)),
                ('num', models.IntegerField()),
                ('translations', models.ManyToManyField(related_name='invoices', to='account.Translation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=64)),
                ('uid', models.CharField(max_length=64)),
                ('note', models.TextField()),
                ('cancellation', models.CharField(max_length=256)),
                ('order_date', models.DateField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('marketplace_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('marketplace', models.CharField(max_length=128)),
                ('tracking_code', models.CharField(max_length=256)),
                ('shipment_service', models.CharField(max_length=128)),
                ('shipment_label', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=64)),
                ('bookkeeping_status', models.CharField(max_length=64)),
                ('is_locked', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer')),
                ('debitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.account')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.invoice')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment')),
                ('services', models.ManyToManyField(related_name='sale_orders', to='product.ProductService')),
                ('translations', models.ManyToManyField(related_name='sales_orders', to='account.Translation')),
                ('user_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=64)),
                ('order_date', models.DateField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('condition_details', models.CharField(max_length=256)),
                ('tracking_code', models.CharField(max_length=256)),
                ('shipment_service', models.CharField(max_length=128)),
                ('shipment_label', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=64)),
                ('is_locked', models.BooleanField(default=False)),
                ('serial_num', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=36)),
                ('creditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.account')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer')),
                ('translations', models.ManyToManyField(related_name='purchase_orders', to='account.Translation')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(max_length=64)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vat', models.CharField(max_length=64)),
                ('manufacturers_serial', models.CharField(max_length=128)),
                ('exp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serialized', to='product.qualitydata')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialized', to='orders.purchaseorder')),
                ('sell_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.salesorder')),
                ('translations', models.ManyToManyField(related_name='serialized', to='account.Translation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prducts', to='warehouse.warehousestorage')),
                ('user_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zerialized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
