# Generated by Django 3.1.6 on 2021-03-17 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '__first__'),
        ('local_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20210311_2212'),
        ('payment', '__first__'),
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True)),
                ('uid', models.CharField(max_length=64)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bookkeeping_status', models.CharField(max_length=64)),
                ('is_locked', models.BooleanField(default=True)),
                ('in_trash', models.BooleanField(default=False, null=True)),
                ('user_owner', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True)),
                ('num', models.CharField(max_length=128, unique=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.file')),
                ('translations', models.ManyToManyField(blank=True, null=True, related_name='invoices', to='account.Translation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_owner', models.CharField(max_length=128)),
                ('key', models.CharField(max_length=64, null=True)),
                ('uid', models.CharField(max_length=64)),
                ('note', models.TextField()),
                ('cancellation', models.CharField(max_length=256, null=True)),
                ('order_date', models.DateField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('marketplace_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('marketplace', models.CharField(max_length=128, null=True)),
                ('tracking_code', models.CharField(max_length=256, null=True)),
                ('shipment_service', models.CharField(max_length=128, null=True)),
                ('shipment_label', models.CharField(max_length=64, null=True)),
                ('shipment_status', models.CharField(max_length=64, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=64)),
                ('bookkeeping_status', models.CharField(max_length=64, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('in_trash', models.BooleanField(default=False, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers', to=settings.AUTH_USER_MODEL)),
                ('debitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to='payment.account')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to='orders.invoice')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to='payment.payment')),
                ('services', models.ManyToManyField(blank=True, related_name='sale_orders', to='product.ProductService')),
                ('translations', models.ManyToManyField(blank=True, related_name='sales_orders', to='account.Translation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_owner', models.CharField(max_length=128)),
                ('uid', models.CharField(max_length=64)),
                ('order_date', models.DateField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('condition_details', models.CharField(max_length=256)),
                ('tracking_code', models.CharField(max_length=256)),
                ('shipment_service', models.CharField(max_length=128)),
                ('shipment_label', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=64)),
                ('is_locked', models.BooleanField(default=False)),
                ('serial_num', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=36)),
                ('in_trash', models.BooleanField(default=False, null=True)),
                ('creditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='payment.account')),
                ('invoices', models.ManyToManyField(blank=True, related_name='purchase_orders', to='product.File')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='payment.payment')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to=settings.AUTH_USER_MODEL)),
                ('translations', models.ManyToManyField(related_name='purchase_orders', to='account.Translation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_owner', models.CharField(max_length=128)),
                ('invoice_template', models.TextField(null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('serial_num', models.CharField(default='', max_length=128, unique=True)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(max_length=64)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('manufacturers_serial', models.CharField(max_length=128)),
                ('in_trash', models.BooleanField(default=False, null=True)),
                ('exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.qualitydata')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.product')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serialized_products', to='orders.purchaseorder')),
                ('sell_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serialized_products', to='orders.salesorder')),
                ('translations', models.ManyToManyField(related_name='serialized', to='account.Translation')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.warehousestorage')),
                ('vat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='local_settings.tax')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128, null=True)),
                ('zip', models.CharField(max_length=48, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('country', models.CharField(max_length=128, null=True)),
                ('tax_id', models.CharField(max_length=128, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='payment.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('var_percent', models.FloatField(null=True)),
                ('vat', models.CharField(choices=[('inkl', 'Inkl.'), ('excl', 'Excl.')], default='', max_length=16)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.account')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='orders.expense')),
                ('translations', models.ManyToManyField(related_name='expense_items', to='account.Translation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('translations', models.ManyToManyField(related_name='expense_categories', to='account.Translation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_tag_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='orders.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='orders.invoice'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='orders.expensesupplier'),
        ),
        migrations.AddField(
            model_name='expense',
            name='translations',
            field=models.ManyToManyField(related_name='expenses', to='account.Translation'),
        ),
    ]
