# Generated by Django 3.1.6 on 2021-02-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='exp',
        ),
    ]
