# Generated by Django 3.1.6 on 2021-02-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_productunit_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='serial_num',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
