# Generated by Django 3.1.6 on 2021-02-16 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productunit_serial_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serialized', to='orders.purchaseorder'),
        ),
    ]
