# Generated by Django 3.1.6 on 2021-02-16 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('orders', '0004_auto_20210216_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prducts', to='warehouse.warehousestorage'),
        ),
    ]
