# Generated by Django 3.1.6 on 2021-02-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_auto_20210220_1024'),
        ('product', '0010_auto_20210215_2123'),
        ('orders', '0006_auto_20210220_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.warehousestorage'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='user_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serialized', to=settings.AUTH_USER_MODEL),
        ),
    ]
