# Generated by Django 3.1.6 on 2021-02-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('orders', '0007_auto_20210220_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='payment.payment'),
        ),
    ]
