# Generated by Django 3.1.6 on 2021-02-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210222_2140'),
        ('orders', '0008_auto_20210220_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.qualitydata'),
        ),
    ]
