# Generated by Django 3.1.6 on 2021-02-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_productunit_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_title', models.CharField(max_length=128)),
                ('tax_description', models.TextField(null=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productunit',
            name='invoice_template',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serialized_products', to='orders.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='sell_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serialized_products', to='orders.salesorder'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='vat',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
