# Generated by Django 3.1.6 on 2021-02-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210224_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='vat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.tax'),
        ),
    ]
