# Generated by Django 3.1.6 on 2021-02-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210224_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='shipment_status',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
