# Generated by Django 3.1.6 on 2021-02-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_salesorder_shipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='invoices',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to='orders.invoice'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tracking_code',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
