# Generated by Django 3.1.6 on 2021-02-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210224_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='num',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
