# Generated by Django 3.1.6 on 2021-02-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210224_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='marketplace_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
