# Generated by Django 3.1.6 on 2021-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_name'),
        ('product', '0011_auto_20210222_2140'),
        ('orders', '0016_auto_20210224_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='translations',
            field=models.ManyToManyField(blank=True, null=True, related_name='invoices', to='account.Translation'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='cancellation',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='services',
            field=models.ManyToManyField(null=True, related_name='sale_orders', to='product.ProductService'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='translations',
            field=models.ManyToManyField(null=True, related_name='sales_orders', to='account.Translation'),
        ),
    ]
