# Generated by Django 3.1.6 on 2021-02-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210211_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=125)),
                ('designer', models.CharField(max_length=125)),
                ('manufacturer', models.CharField(blank=True, max_length=125, null=True)),
                ('bullet_point', models.CharField(max_length=10)),
                ('merchant_catalog_number', models.CharField(max_length=25)),
                ('serial_number_req', models.CharField(max_length=125)),
                ('legal_disclamer', models.TextField()),
                ('mfr_part_number', models.CharField(max_length=25)),
                ('search_terms', models.TextField()),
                ('platinum_keywords', models.TextField()),
                ('browse_node', models.CharField(max_length=126)),
                ('memorabilia', models.CharField(max_length=126)),
                ('autographed', models.BooleanField(default=False)),
                ('other_item_attributes', models.CharField(max_length=256)),
                ('target_audience', models.CharField(max_length=125)),
                ('subject_content', models.TextField()),
                ('TSD_age_warning', models.CharField(max_length=24)),
                ('TSD_warning', models.CharField(max_length=128)),
                ('TSD_language', models.CharField(max_length=24)),
                ('product_data', models.CharField(max_length=512)),
                ('variation', models.CharField(max_length=128)),
                ('exp', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='serialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productdata'),
        ),
    ]
