# Generated by Django 3.1.6 on 2021-02-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210213_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='TSD_age_warning',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='TSD_language',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='TSD_warning',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='autographed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='brand',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='browse_node',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='bullet_point',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='designer',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='exp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='legal_disclamer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='memorabilia',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='merchant_catalog_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='mfr_part_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='other_item_attributes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='platinum_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='product_data',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='search_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='serial_number_req',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='subject_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='target_audience',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='variation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
