# Generated by Django 3.1.6 on 2021-02-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210213_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='qualityimage',
            name='exp',
        ),
        migrations.AddField(
            model_name='product',
            name='alternate_images',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.ProductImage'),
        ),
        migrations.AddField(
            model_name='qualitydata',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='quality', to='product.QualityImage'),
        ),
    ]
