# Generated by Django 3.1.6 on 2021-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210214_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quality_data',
        ),
        migrations.AddField(
            model_name='product',
            name='quality_data',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.QualityData'),
        ),
    ]
