# Generated by Django 3.1.6 on 2021-02-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_productunit_exp'),
        ('product', '0007_auto_20210215_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerilizedQualityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(blank=True, related_name='quality', to='product.ProductImage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='qualitydata',
            name='images',
        ),
        migrations.DeleteModel(
            name='QualityImage',
        ),
        migrations.AddField(
            model_name='serilizedqualitydata',
            name='quality_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialized_quality', to='product.qualitydata'),
        ),
        migrations.AddField(
            model_name='serilizedqualitydata',
            name='serialized_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_data', to='orders.productunit'),
        ),
    ]
