# Generated by Django 3.1.6 on 2021-02-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210215_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualitydata',
            name='quality_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
