# Generated by Django 3.1.6 on 2021-02-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210215_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quality_data',
            new_name='exp',
        ),
    ]
