# Generated by Django 3.1.6 on 2021-02-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210215_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitydata',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='quality', to='product.ProductImage'),
        ),
        migrations.DeleteModel(
            name='SerilizedQualityData',
        ),
    ]
